source "https://rubygems.org"

# gem "jekyll", "~> 4.2.0"
gem "github-pages", group: :jekyll_plugins
gem "webrick", "~> 1.7"
gem "csv"
gem "base64"
gem "bigdecimal"
gem "logger"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
