source "https://rubygems.org"

gem "webrick", "~> 1.7"
gem "csv", "~> 3.3"
gem "base64", "~> 0.2"
gem "bigdecimal", "~> 3.1"
gem "logger", "~> 1.6"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-gist", "~> 1.5"
  gem "github-pages", "~> 232"
end
