# Setup
title:               Computer Vision Project | Group 1
description:         'Group 1: Pedestrian Detection. How can we ensure robust and safe pedestrian detection in a variety of environments?'
paginate:            1
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax