# Setup
title:               Pedestrian Detection
description:         'Pedestrian Detection Blog Post'
paginate:            1
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
